### ISSUE TITLE
支持 eslint 9.0.0

### ISSUE THREAD

**Issue by suiyun39** [suiyun39/eslint-config-rakko#12]
相关 PR：#11

存在兼容性问题的插件：

- [x] `eslint-flat-config-viewer` - 此工具已被整合进 eslint 9.0.0 中，完成更新后移除即可。
- [x] `@stylistic/eslint-plugin` - 此插件的依赖 `@typescript-eslint/utils` 存在兼容性问题，需要关注 `typescript-eslint` 的更新
- [x] `eslint-plugin-i` - import-js/eslint-plugin-import#2948
- [ ] `eslint-plugin-jsx-expressions` - 依赖于 `@typescript-eslint/parser` 且 repo 非活跃状态，考虑 `typescript-eslint` 更新后在 repo 中自行维护此规则
- [x] `eslint-plugin-react` - jsx-eslint/eslint-plugin-react#3699
- [x] `eslint-plugin-react-hooks` - facebook/react#28773
- [x] `eslint-plugin-solid` - solidjs-community/eslint-plugin-solid#137
- [x] `typescript-eslint` - typescript-eslint/typescript-eslint#8211
